apiVersion: v1
metadata:
  name: gmail-rest-api-kub
  kind: Pod
spec:
  template:
    metadata:
      labels:
        name: gmail-rest-api
    spec:
      containers:
      - name: gmail-rest-api-container
        image: gmail_rest_api
        ports:
        - containerPort: 80
          name: "http-server"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /container_volume
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /tmp/container_volume
